[package]
name = "gossip-glomers"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
color-eyre = "0.6.3"
thiserror = "2.0.12"

[[bin]]
name = "echo"
path = "src/bin/echo.rs"
